apiVersion: v1
kind: Service
metadata:
  name: flask-node-deployment
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: 5000
  selector:
    app: flasknode
  type: LoadBalancer
